// MVC - MODEL VIEW CONTROLLER
/** VIEW - INTERFACE QUE O USUÁRIO INTERAGE 
 * CONTROLLER - DEFINE AS REGRAS DE NEGOCIO, DEFINE O QUE DEVE OU NÃO ACONTECER  
 * MODEL - TRATA OS DADOS, INTEREGE COM O BANCO DE DADOS, ACESSA OS MESMO
*/

let calculator = new CalcController();

